#spring.security.user.password: password # ????? ??? ???????? ????? ?????? ?????????? ?????? ??? security
spring:
  datasource:
    url: jdbc:tc:postgresql:16:///sandbox?TC_DAEMON=true # /// тре слеша значит что хост и порт игнорируем
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml